# Please see https://marketplace.visualstudio.com/items?itemName=humao.rest-client for documentation

@hostname = http://localhost
@port = 8080
@host = {{hostname}}:{{port}}

### Logins as Admin User
# @name login
POST {{host}}/login
Content-Type: application/json

{
  "username": "admin_1569417064968@edugoai.com",
  "password": "admin"
}

### Logins as standard User
# @name login
POST {{host}}/login
Content-Type: application/json

{
  "username": "standard_1569417064991@edugoai.com",
  "password": "standard"
}

### Create a new meeting room only available for admins
# @name createNewMeetingRoom
POST {{host}}/room
Content-Type: application/json
access-token: {{login.response.body.token}}

{
  "name": "Beijing",
  "code": "C003BEIJING",
  "description": "Meeting room for the board members",
  "capacity": 10
}

### Update a meeting room only available for admins
# @name updateMeetingRoom
PATCH {{host}}/room
Content-Type: application/json
access-token: {{login.response.body.token}}

{
  "name": "Beijing",
  "code": "C003BEIJING",
  "description": "Meeting room for the board members",
  "capacity": 10
}

### Book a meeting Room
# @name bookRoom
POST {{host}}/room/2/book
Content-Type: application/json
access-token: {{login.response.body.token}}

{
  "bookingStart": [2019, 9, 30, 8, 30],
  "bookingEnd": [2019, 9, 30, 9, 0],
  "title": "Board Meeting",
  "purpose": "Q3 and Q3 follow up"
}